# -*- coding: utf-8 -*-

def process_gro_file(input_file):
    with open(input_file, 'r') as file:
        lines = file.readlines()

    output_filename = input_file.replace('.gro', '_water_molecules.txt')

    with open(output_filename, 'w') as output_file:
        time = None
        molecule_data = []
        last_molecule_id = None

        for line in lines:
            if "Generated by trjconv" in line:
                # Antes de processar um novo frame, escreva os dados restantes do último frame
                if molecule_data:
                    output_file.write("W{}: H1 {} O {} M {} H2 {}\n".format(
                        molecule_data['id'], molecule_data['H1'], molecule_data['O'],
                        molecule_data['M'], molecule_data['H2']))
                    molecule_data = []

                # Extrair o tempo, converter para nanossegundos e escrever no arquivo
                time = line.split('t=')[-1].strip()
                time_in_ns = float(time) / 1000  # Converter ps para ns
                output_file.write("Time: {:.3f}\n".format(time_in_ns))  # Escrever com 3 casas decimais

            elif len(line) >= 44:  # Ensuring it's long enough
                molecule_id = int(line[0:5].strip())
                atom_name = line[10:15].strip()
                x = line[20:28].strip()
                y = line[28:36].strip()
                z = line[36:44].strip()
                coords = "({}, {}, {})".format(x, y, z)

                if atom_name == "OW":  # Início de uma nova molécula de água
                    if molecule_data and molecule_id != last_molecule_id:  # Escrever a molécula anterior se uma nova for encontrada
                        output_file.write("W{}: H1 {} O {} M {} H2 {}\n".format(
                            molecule_data['id'], molecule_data['H1'], molecule_data['O'],
                            molecule_data['M'], molecule_data['H2']))
                    # Coletar dados para uma nova molécula
                    molecule_data = {'id': molecule_id, 'O': coords}
                    last_molecule_id = molecule_id
                elif atom_name == "HW1":
                    molecule_data['H1'] = coords
                elif atom_name == "HW2":
                    molecule_data['H2'] = coords
                elif atom_name == "MW":
                    molecule_data['M'] = coords

            elif len(line.split()) == 1 and molecule_data:  # Fim dos dados atômicos para este frame
                # Escrever a última molécula do frame
                output_file.write("W{}: H1 {} O {} M {} H2 {}\n".format(
                    molecule_data['id'], molecule_data['H1'], molecule_data['O'],
                    molecule_data['M'], molecule_data['H2']))
                molecule_data = []

        # Garantir que a última molécula do frame final seja escrita
        if molecule_data:
            output_file.write("W{}: H1 {} O {} M {} H2 {}\n".format(
                molecule_data['id'], molecule_data['H1'], molecule_data['O'],
                molecule_data['M'], molecule_data['H2']))

if __name__ == "__main__":
    input_file = '1_teste.gro'  # Substitua pelo nome real do arquivo de entrada
    process_gro_file(input_file)