# -*- coding: utf-8 -*-

import re

def parse_coordinates(file_content):
    times = []
    residues = []
    coordinates = []
    current_time = None
    current_coords = []

    for line in file_content.splitlines():
        # Detect the time stamp
        if "Generated by" in line:
            if current_time is not None and current_coords:
                coordinates.append(current_coords)
            current_time = float(re.findall(r"t= *([\d.]+)", line)[0])
            times.append(current_time)
            current_coords = []
        # Detect atom coordinates
        elif re.match(r'\s*\d+\w+\s+[A-Z]+\s+\d+', line):
            parts = line.split()
            residue_atom = parts[0] + "_" + parts[1]
            if residue_atom not in residues:
                residues.append(residue_atom)
            # Append the x, y, z coordinates
            current_coords.extend([float(parts[3]), float(parts[4]), float(parts[5])])

    # Append the last set of coordinates
    if current_coords:
        coordinates.append(current_coords)

    return times, residues, coordinates


def format_output(times, residues, coordinates):
    formatted = []
    # Format the class (times)
    #formatted.append("Class:\n" + ";".join(f"{t/1000:.1f}" for t in times) + "\n")

    # Format the residue and atom labels
    #formatted.append("Residue and atom:\n" + ";".join(f"{r}_x;{r}_y;{r}_z" for r in residues) + "\n")

    # Format the coordinates for each time step
    #formatted.append("Coordinates of each atom by time on each line:")
    for coords in coordinates:
        formatted.append(";".join(f"{c:.3f}" for c in coords))

    return "\n".join(formatted)


# Example usage
with open('teste.gro', 'r') as f:
    file_content = f.read()

times, residues, coordinates = parse_coordinates(file_content)
output = format_output(times, residues, coordinates)

with open('teste_pca_a.txt', 'w') as f:
    f.write(output)